name: HippoTab
version: '$version'

main: net.mwtw.hippoTab.Core
api-version: '1.21'
load: POSTWORLD
depend: [PlaceholderAPI]
softdepend: [Vault, VaultUnlocked, packetevents]

commands:
  hippotab:
    description: Main command for HippoTab
    usage: /<command> reload
    aliases: [htab]

permissions:
  hippotab.reload:
    description: Allows reloading HippoTab configuration
    default: op
